[package]
name = "rpi0_plant_monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linux-embedded-hal = "0.3.2"
bme280 = "0.2.1"
paho-mqtt = "0.10.0"
rumqttc = "0.10.0"